apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    name: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    exporters:
      otlp:
        endpoint: "otel-infra.sam-app.ro:4317"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
      telemetry:
        logs:
          level: "info"
